### ISSUE TITLE
Request for Spark! Tech Resources for Oasis Wellbeing - Mental Health Application

### ISSUE THREAD

**Issue by vishwas21** [BU-Spark/se-oasis#10]
Team Members:
Vishwas Bhaktavatsala (@vishwas21 ) - [vishwasb@bu.edu](mailto:vishwasb@bu.edu)
Harshitha Tumkur Kailasa Murthy (@harshithatk33 ) - [harshutk@bu.edu](mailto:harshutk@bu.edu)
Erwin Pimentel (@RevibeZ ) - [erwinp@bu.edu](mailto:erwinp@bu.edu)

Hi @IanSaucy,

We would like to request a Google Cloud Account for our Oasis Project. Currently, we are using our personal account to host events and integrate firebase. Below are the services which we are using right now.
Cloud Functions
Cloud Pub/Sub
Firebase Authentication
Firestore Database - Firebase
Service Account
IAM

and we plan on using the following services for deploying the application
Google Compute Engine
Google App Engine (Maybe)

We would like permissions for all these services along with their APIs. Please help us on this.

Thanks

**Comment by vishwas21** [comment]
@IanSaucy Please let us if this would be possible as our personal accounts are restricted for certain functionalities we are using.

**Comment by IanSaucy** [comment]
Created and added you all as owners of the project. Located here: https://console.cloud.google.com/welcome?hl=en-AU&project=se-oasis

You need to keep documentation about every service that you setup. In addition, how they are connected(architecture diagram). Lastly, you need to document how to deploy and access each service. All of this should be saved in your repo(unless it contains secrets, then use google drive)

Lastly, if you are using services that are going to cost more than 10-20$ a month please check with Langdon.

**Comment by vishwas21** [comment]
Thanks @IanSaucy. We will keep the documents udpated.
