### ISSUE TITLE
Request for Spark! Tech Resources for Oasis Wellbeing - Mental Health Application

### ISSUE THREAD

**Issue by vishwas21** [BU-Spark/se-oasis#3]
Team Members:
Vishwas Bhaktavatsala (@vishwas21 ) - [vishwasb@bu.edu](mailto:vishwasb@bu.edu)
Harshitha Tumkur Kailasa Murthy (@harshithatk33 ) - [harshutk@bu.edu](mailto:harshutk@bu.edu)
Erwin Pimentel (@RevibeZ ) - [erwinp@bu.edu](mailto:erwinp@bu.edu)

Currently would require a Cloud SQL Server (PostgreSQL) to start our inital connections code

We plan to use this database to store all the user data along with the journal data

Would like to get this before our midterm presentation so that we have sometime concrete to show.

**Comment by IanSaucy** [comment]
Are you married to cloud SQL? We have another postgres service we normally use because it's much cheaper

**Comment by vishwas21** [comment]
@IanSaucy We are not completely set on Cloud SQL, we can work with any other postgres server as well. Please provide us all the required details for this, we will work with it.
Thanks

**Comment by IanSaucy** [comment]
Setup, messaged you on Slack with the connection details
